image:
    file: .gitpod.dockerfile
ports:
- port: 8888
  onOpen: open-browser
- port: 8080
  onOpen: notify
tasks:
- init: pip3 install opencv-python==4.4.0.42 opencv-contrib-python && jupyter notebook Jupyter/ --NotebookApp.allow_origin=\'$(gp url 8888)\' --ip='*' --NotebookApp.token='' --NotebookApp.password=''
