#image:
#    file: .gitpod.dockerfile
ports:
- port: 8888
  onOpen: open-browser
- port: 8080
  onOpen: notify
tasks:
- command: jupyter notebook jupyter/ --NotebookApp.allow_origin=\'$(gp url 8888)\' --ip='*' --NotebookApp.token='' --NotebookApp.password=''
